[2024-08-02T14:25:39.230+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-02T14:25:39.240+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline_supermarket_2.copy_table_dim_departments manual__2024-08-02T07:09:40.143577+00:00 [queued]>
[2024-08-02T14:25:39.245+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline_supermarket_2.copy_table_dim_departments manual__2024-08-02T07:09:40.143577+00:00 [queued]>
[2024-08-02T14:25:39.246+0700] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-02T14:25:39.268+0700] {taskinstance.py:2330} INFO - Executing <Task(PostgresOperator): copy_table_dim_departments> on 2024-08-02 07:09:40.143577+00:00
[2024-08-02T14:25:39.270+0700] {standard_task_runner.py:64} INFO - Started process 15169 to run task
[2024-08-02T14:25:39.273+0700] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'data_pipeline_supermarket_2', 'copy_table_dim_departments', 'manual__2024-08-02T07:09:40.143577+00:00', '--job-id', '134', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline_supermarket_2.py', '--cfg-path', '/tmp/tmpzc5yvewf']
[2024-08-02T14:25:39.274+0700] {standard_task_runner.py:91} INFO - Job 134: Subtask copy_table_dim_departments
[2024-08-02T14:25:39.307+0700] {task_command.py:426} INFO - Running <TaskInstance: data_pipeline_supermarket_2.copy_table_dim_departments manual__2024-08-02T07:09:40.143577+00:00 [running]> on host DESKTOP-RHVHV7A.
[2024-08-02T14:25:39.374+0700] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='data_pipeline_supermarket_2' AIRFLOW_CTX_TASK_ID='copy_table_dim_departments' AIRFLOW_CTX_EXECUTION_DATE='2024-08-02T07:09:40.143577+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-02T07:09:40.143577+00:00'
[2024-08-02T14:25:39.375+0700] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-02T14:25:39.383+0700] {sql.py:282} INFO - Executing: 
        COPY dim_departments TO '/mnt/f/AllCode/Data Engineer/dim_departments.csv' CSV HEADER;
        
[2024-08-02T14:25:39.386+0700] {base.py:84} INFO - Using connection ID 'postgres_supermarket' for task execution.
[2024-08-02T14:25:39.402+0700] {base.py:84} INFO - Using connection ID 'postgres_supermarket' for task execution.
[2024-08-02T14:25:39.434+0700] {sql.py:495} INFO - Running statement: 
        COPY dim_departments TO '/mnt/f/AllCode/Data Engineer/dim_departments.csv' CSV HEADER;
        , parameters: None
[2024-08-02T14:25:39.435+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-02T14:25:39.436+0700] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/providers/common/sql/operators/sql.py", line 288, in execute
    output = hook.run(
  File "/usr/local/lib/python3.10/dist-packages/airflow/providers/common/sql/hooks/sql.py", line 442, in run
    self._run_command(cur, sql_statement, parameters)
  File "/usr/local/lib/python3.10/dist-packages/airflow/providers/common/sql/hooks/sql.py", line 500, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedTable: relation "dim_departments" does not exist

[2024-08-02T14:25:39.438+0700] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=data_pipeline_supermarket_2, task_id=copy_table_dim_departments, run_id=manual__2024-08-02T07:09:40.143577+00:00, execution_date=20240802T070940, start_date=20240802T072539, end_date=20240802T072539
[2024-08-02T14:25:39.459+0700] {standard_task_runner.py:110} ERROR - Failed to execute job 134 for task copy_table_dim_departments (relation "dim_departments" does not exist
; 15169)
[2024-08-02T14:25:39.485+0700] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-02T14:25:39.493+0700] {logging_mixin.py:188} WARNING - /usr/local/lib/python3.10/dist-packages/airflow/models/baseoperator.py:1297 AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `airflow.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
[2024-08-02T14:25:39.501+0700] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-02T14:25:39.502+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
