[2024-08-02T13:50:41.483+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-02T13:50:41.515+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline_supermarket.airbyte_check_sync_0 manual__2024-08-02T03:30:51.725028+00:00 [queued]>
[2024-08-02T13:50:41.530+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline_supermarket.airbyte_check_sync_0 manual__2024-08-02T03:30:51.725028+00:00 [queued]>
[2024-08-02T13:50:41.530+0700] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-08-02T13:50:41.565+0700] {taskinstance.py:2330} INFO - Executing <Task(AirbyteJobSensor): airbyte_check_sync_0> on 2024-08-02 03:30:51.725028+00:00
[2024-08-02T13:50:41.572+0700] {standard_task_runner.py:64} INFO - Started process 5786 to run task
[2024-08-02T13:50:41.584+0700] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'data_pipeline_supermarket', 'airbyte_check_sync_0', 'manual__2024-08-02T03:30:51.725028+00:00', '--job-id', '93', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline_supermarket.py', '--cfg-path', '/tmp/tmpugyyy8ve']
[2024-08-02T13:50:41.586+0700] {standard_task_runner.py:91} INFO - Job 93: Subtask airbyte_check_sync_0
[2024-08-02T13:50:41.686+0700] {task_command.py:426} INFO - Running <TaskInstance: data_pipeline_supermarket.airbyte_check_sync_0 manual__2024-08-02T03:30:51.725028+00:00 [running]> on host DESKTOP-RHVHV7A.
[2024-08-02T13:50:41.846+0700] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='data_pipeline_supermarket' AIRFLOW_CTX_TASK_ID='airbyte_check_sync_0' AIRFLOW_CTX_EXECUTION_DATE='2024-08-02T03:30:51.725028+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-02T03:30:51.725028+00:00'
[2024-08-02T13:50:41.847+0700] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-02T13:50:41.888+0700] {baseoperator.py:400} WARNING - AirbyteJobSensor.execute cannot be called outside TaskInstance!
[2024-08-02T13:50:41.898+0700] {base.py:84} INFO - Using connection ID 'airflow-call-to-airbyte-example' for task execution.
[2024-08-02T13:50:42.512+0700] {airbyte.py:108} INFO - Job 69 completed successfully.
[2024-08-02T13:50:42.513+0700] {base.py:294} INFO - Success criteria met. Exiting.
[2024-08-02T13:50:42.513+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-02T13:50:42.529+0700] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=data_pipeline_supermarket, task_id=airbyte_check_sync_0, run_id=manual__2024-08-02T03:30:51.725028+00:00, execution_date=20240802T033051, start_date=20240802T065041, end_date=20240802T065042
[2024-08-02T13:50:42.565+0700] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-08-02T13:50:42.579+0700] {logging_mixin.py:188} WARNING - /usr/local/lib/python3.10/dist-packages/airflow/models/baseoperator.py:1297 AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `airflow.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
[2024-08-02T13:50:42.619+0700] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-02T13:50:42.620+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
