[2024-08-03T11:03:49.898+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-03T11:03:49.908+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline_supermarket_2.copy_table_dim_departments manual__2024-08-03T03:55:46.320694+00:00 [queued]>
[2024-08-03T11:03:49.914+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline_supermarket_2.copy_table_dim_departments manual__2024-08-03T03:55:46.320694+00:00 [queued]>
[2024-08-03T11:03:49.915+0700] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-08-03T11:03:49.939+0700] {taskinstance.py:2330} INFO - Executing <Task(PostgresOperator): copy_table_dim_departments> on 2024-08-03 03:55:46.320694+00:00
[2024-08-03T11:03:49.943+0700] {standard_task_runner.py:64} INFO - Started process 24662 to run task
[2024-08-03T11:03:49.945+0700] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'data_pipeline_supermarket_2', 'copy_table_dim_departments', 'manual__2024-08-03T03:55:46.320694+00:00', '--job-id', '193', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline_supermarket_2.py', '--cfg-path', '/tmp/tmpotf90fd7']
[2024-08-03T11:03:49.946+0700] {standard_task_runner.py:91} INFO - Job 193: Subtask copy_table_dim_departments
[2024-08-03T11:03:50.002+0700] {task_command.py:426} INFO - Running <TaskInstance: data_pipeline_supermarket_2.copy_table_dim_departments manual__2024-08-03T03:55:46.320694+00:00 [running]> on host DESKTOP-RHVHV7A.
[2024-08-03T11:03:50.069+0700] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='data_pipeline_supermarket_2' AIRFLOW_CTX_TASK_ID='copy_table_dim_departments' AIRFLOW_CTX_EXECUTION_DATE='2024-08-03T03:55:46.320694+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-03T03:55:46.320694+00:00'
[2024-08-03T11:03:50.070+0700] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-03T11:03:50.079+0700] {sql.py:282} INFO - Executing: 
        COPY dim_departments TO 'F:/AllCode/Data Engineer/dim_departments.csv' CSV HEADER;
        
[2024-08-03T11:03:50.083+0700] {base.py:84} INFO - Using connection ID 'postgres_supermarket' for task execution.
[2024-08-03T11:03:50.099+0700] {base.py:84} INFO - Using connection ID 'postgres_supermarket' for task execution.
[2024-08-03T11:03:50.131+0700] {sql.py:495} INFO - Running statement: 
        COPY dim_departments TO 'F:/AllCode/Data Engineer/dim_departments.csv' CSV HEADER;
        , parameters: None
[2024-08-03T11:03:50.134+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-03T11:03:50.135+0700] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/providers/common/sql/operators/sql.py", line 288, in execute
    output = hook.run(
  File "/usr/local/lib/python3.10/dist-packages/airflow/providers/common/sql/hooks/sql.py", line 442, in run
    self._run_command(cur, sql_statement, parameters)
  File "/usr/local/lib/python3.10/dist-packages/airflow/providers/common/sql/hooks/sql.py", line 500, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedTable: relation "dim_departments" does not exist

[2024-08-03T11:03:50.139+0700] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=data_pipeline_supermarket_2, task_id=copy_table_dim_departments, run_id=manual__2024-08-03T03:55:46.320694+00:00, execution_date=20240803T035546, start_date=20240803T040349, end_date=20240803T040350
[2024-08-03T11:03:50.208+0700] {standard_task_runner.py:110} ERROR - Failed to execute job 193 for task copy_table_dim_departments (relation "dim_departments" does not exist
; 24662)
[2024-08-03T11:03:50.243+0700] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-03T11:03:50.252+0700] {logging_mixin.py:188} WARNING - /usr/local/lib/python3.10/dist-packages/airflow/models/baseoperator.py:1297 AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `airflow.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
[2024-08-03T11:03:50.260+0700] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-03T11:03:50.279+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
